builds:
  - binary: dnsovertlsproxy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archive:
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x64
    386: x86
    darwin: macos
  files:
    - LICENSE

brew:
  github:
    owner: 4d63
    name: homebrew-dnsovertlsproxy
  commit_author:
    name: Leigh McCulloch
    email: leigh@mcchouse.com
  folder: Formula
  homepage: "https://4d63.com/dnsovertlsproxy"
  description: A simple DNS over TLS proxy.
  test: |
    system "#{bin}/dnsovertlsproxy -version"
  install: |
    bin.install "dnsovertlsproxy"
  plist: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>KeepAlive</key>
      <true/>
      <key>Label</key>
      <string>#{plist_name}</string>
      <key>ProgramArguments</key>
      <array>
        <string>-listen=:53</string>
        <string>-server=1.1.1.1:853</string>
      </array>
      <key>RunAtLoad</key>
      <true/>
    </dict>
    </plist>
